version: "3"
services:
    database:
        image: "postgres:14"
        volumes:
          - ./data:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
          - "5432:5432"
        expose:
          - "5432"
    api:
        build: .
        ports: 
          - ${APP_PORT}:${APP_PORT}
        depends_on:
          - "database"